logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http.client: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  output:
    ansi:
      enabled: always
  flyway:
    clean-disabled: false

server:
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoint:
    health:
      show-details: always
