spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wow_test
    username: wow
    password: wow
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: false
